### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by GDN-08** [iMicknl/python-overkiz-api#1111]
Hello,

first, thanks for sharing all your findings on overkiz for Cozytouch.
I have 2 Cozytouch accounts (2 different houses):
- The first one has been created 2 years ago. It is for a house where 6 Atlantic(thermor) hearted are connected through a Cozytouch bridge.
- The second account, created some days ago, is for another house where I only have an Atlantic Aqueo water heater connected through WiFI.

1- I can successfully log in cozytouch app with both account (and can manage my devices)
2- This python script works fine with the first account (house with cozytouch bridge)
3- I’m facing a « Bad credentials » error when tryin to use this script with the second account.

Am I missing something ? Is there a different overkiz/Atlantic server for WiFi-managed devices ?
Thanks for your help

**Comment by iMicknl** [comment]
WiFi managed devices don’t use the Overkiz servers, hence you can’t login there. In our Home Assistant integration, you will see a nice error message, but this is not implemented for the underlying library.
