### ISSUE TITLE
Sauter - Kelud smart towel heater (direct WiFi through CozyTouch App) does not show

### ISSUE THREAD

**Issue by AuroreVgn** [iMicknl/python-overkiz-api#1204]
Hi,
I bought a Sauter Kelud smart towel heater. It has direct WiFi connection (no need to use CozyTouch bridge) through CozyTouch App.
Do you think it will be possible to get its data?
Thanks.
A

**Comment by iMicknl** [comment]
This is not supported by this library. Most likely you can reverse engineer the traffic, but since it is not using Overkiz, this is not the scope of this library.
