### ISSUE TITLE
Rexel Energeasy Connect does not work in Overkiz integration

### ISSUE THREAD

**Issue by Eridani78** [iMicknl/python-overkiz-api#1307]
Hi Mickael,

According to this:

 https://github.com/home-assistant/core/issues/70869

 it seems that Overkiz integration does not work anymore with Rexel Energeasy Connect.

But Rexel Energeasy Connect is still listed in the supported servers of this lib ?
Seems to be not consistent.

Could you please advise ?
Is there any other listed servers in the list that are not anymore supported ?

Thanks in advance

**Comment by iMicknl** [comment]
@Eridani78 we forgot to remove it here indeed. In theory we still support Rexel Energeasy Connect, if you have 'steal' your token after login via Rexel and use this to create a separate account on the Overkiz server. Not sure if it is still possible to sniff the current request the app makes.

The main issue is that Rexel moved to a new authentication method (Azure Entra ID), which we cannot leverage.

**Comment by Eridani78** [comment]
Hi @iMicknl,

Thank you for your detailed reply.
I saw that clarifications were added to the lib presentation.
:+1:
