### ISSUE TITLE
Since pyoverkiz 1.3.0 the API is not working with SIMU devices

### ISSUE THREAD

**Issue by daveixis** [iMicknl/python-overkiz-api#403]
Hello,

As a big fan of the API I have recently upgraded from pyoverkiz 1.2.0 to 1.3.6 and I noticed that the api no longer works with SIMU devices (using LiveIn2 gateway) starting from version 1.3.0. I assume that comes from the fact of introduction of OAuth as I'm getting error "error.invalid.grant" starting with version 1.3.0, when using "somfy_europe" servers.

Would it possible to add specific server details for SIMU (LiveIn2) devices?

Thank you in advance.

Best Regards,
Dawid

**Comment by iMicknl** [comment]
Do you use the Python API directly in a project? Or do you consume this via Home Assistant?

I have never heard about the LiveIn2 gateway / SIMU devices. Can you provide a bit more information? Do you have a link to the normal vendor app? (iOS / Android?)

**Comment by daveixis** [comment]
Thank you for a quick reply, I was not expecting that :)

I'm using the custom ha-tahoma in Home Assistant, but also previously experimented a bit with the library in python too. But currently almost exclusively via HA. Latest few HA updates with overkiz included broke my integrations with all shutter devices at home.

Here is the link to the LiveIn2 application:
https://play.google.com/store/apps/details?id=com.simu.livein2&hl=en&gl=US

SIMU looks to be popular in France as many devices I have seen are based on Hz and BHz protocols or maybe some installers in the area are using them as alternative to Somfy devices.

The device I have is this one (looks like a Kizbox ... I wonder how the firmware is different ;) ):
https://www.livein.simu.com/en/

**Comment by daveixis** [comment]
I did a quick check of the app using apktool and found:
...
<string name="default_server_url">https://ha101-1.overkiz.com</string>

... no idea how to find manufacturer as I don't know the APIs and I'm not an Android developer or a good developer as such ;)

**Comment by iMicknl** [comment]
I will make sure this one is added to the library (and thus integration). Interesting to see that they use the tahomalink server (https://ha101-1.overkiz.com), but that they don't support the new authentication.

**Comment by daveixis** [comment]
Indeed, interesting. Another strange thing is that when I login there with my SIMU credentials I'm getting:
![image](https://user-images.githubusercontent.com/101296514/157639357-bc90540d-f6bb-4acb-8681-ffa9e999a70e.png)
... but it is working from the Android app, so the app must be setting parameters in the call.

I'm ready to test the pyoverkiz whenever there is a new version available. Thank you again for the quick help!
