### ISSUE TITLE
refresh_states function no longer work

### ISSUE THREAD

**Issue by flzicmu** [iMicknl/python-overkiz-api#435]
Hi,
Since 2022-03-29 08:36:51 UTC  (apparently after a server maintenance) the function « refresh_states() » in client.py no longer works. I get an exception with the message «Content type 'application/octet-stream' not supported ». I use the the 1.3.10 release but same result with 1.3.12 and 1.3.13.
Thanks,
Franck.

**Comment by iMicknl** [comment]
@flzicmu thanks for reporting! What is your use-case for calling refresh_states? (and how often do you call it).

**Comment by flzicmu** [comment]
I use overKizClient with "somfy_europe" server, user and password. I used the refresh_state function every 30s for several months without problem.

**Comment by iMicknl** [comment]
@flzicmu but why do you use that? I don't think it is a best practice to call this function every 30 seconds... This will introduce an (unnecessary?)  load on the Somfy servers.

**Comment by flzicmu** [comment]
I use this function because it is the only way I've found  to force the tahoma to refresh the state of my connected lock. Otherwise the tahoma never ask the server "somfykeys" to refresh the state of the lock and give the last state it has. There is not event generated when the lock state change.
