### ISSUE TITLE
Undocumented backwards incompatibility in version 1.4.0

### ISSUE THREAD

**Issue by eXceediDeaL** [iMicknl/python-overkiz-api#477]
Hello, I found that the most recent version **1.4.0** of pyoverkiz probably introduces some **breaking changes**, which are not recorded in release notes.

1. Parameter position changing, would cause unexpected argument passing if calling the function with all positional arguments.
     1. `session` from 5th to 6th in function `pyoverkiz.client.OverkizClient.__init__`
     2. Swap `name` and `timestamp` in function `pyoverkiz.models.Event.__init__`
     3. Move one position right of `qualified_name`, `type`, `values` in function `pyoverkiz.models.StateDefinition.__init__`
2. Add optional parameters, would cause inconsistent signature if a subclass overrides the method.
     1. Parameter `widget_name` in method `pyoverkiz.models.Device.__init__`
     2. Parameter `token` in method `pyoverkiz.client.OverkizClient.__init__`
     3. Parameter `name` in method `pyoverkiz.models.StateDefinition.__init__`

To make it easier to understand the impact of the breaking changes, I write a short code snippet that reproduces the breaking changes.
The following code runs well in 1.3.14 but gets crashed in 1.4.0.

```python
pyoverkiz.models.Event(1, EventName.ACTION_GROUP_CREATED)
# parameter `name` accepts argument `1` (the timestamp in 1.3.14) 
# and parameter `timestamp` accepts argument from `EventName.ACTION_GROUP_CREATED` (the name in 1.3.14).
```

Maybe recording these changes in release notes helps to avoid user confusion during updating this version?

Kind regrads,

@eXceediDeaL

**Comment by iMicknl** [comment]
Thanks for reporting @eXceediDeaL! And sorry if we caused you any trouble, I will make sure that we try to avoid breaking changes and/or adhere to [semver](https://semver.io/) and note it in the changelog.

Out of interest, what are you using the Python library for?
