### ISSUE TITLE
/exec/apply delivers http error 415 (unsupported mediatype) if charset is defined

### ISSUE THREAD

**Issue by ChristianRiedl** [iMicknl/python-overkiz-api#529]
I am currently implementing a .NET version of the Tahoma (local) API. I got an unsupported mediatype error on **"/exec/apply"**.
The reason was the charset parameter of the "application/json" content type which is created by default in .NET. 

Usually the **ContentType** header allows to specify also a character set (like charset=UTF-8). 
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

I was able to implement a work arround, but I think the Tahoma server  (new Tahoma Switch)  should accept a charset parameter for the content type.

**Comment by tetienne** [comment]
Hi,

This repository is not affiliated with Somfy or Overkiz.

To suggest improvement to the API, open an issue on https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode
