### ISSUE TITLE
Excessing DNS query for tahomalink.com

### ISSUE THREAD

**Issue by mlankamp** [iMicknl/python-overkiz-api#538]
This is probably because of a configuration at the Somfy side (their dns records have a ttl of 0), this causes the lookup to happen almost every second (in home assistant). Can you do some internal caching?

<img width="286" alt="image" src="https://user-images.githubusercontent.com/8513556/178108967-7275a75a-4e48-4d31-badb-42ee9e98e55f.png">

**Comment by iMicknl** [comment]
Could you check if `https://ha101-1.overkiz.com` has the same behavior? I would not be in favor of caching the DNS in the integration, since this should be fixed on Somfy's side indeed...

**Comment by mlankamp** [comment]
The DNS record seems to be better:
`ha101-1.overkiz.com.    3177    IN      A       178.32.15.131`

The TTL is `3177` seconds, so this seems to be better

**Comment by iMicknl** [comment]
Thanks @mlankamp! I will look if we can switch to this server, this will probably also save us from the certificate expired issue we have every year with tahomalink.com...
