### ISSUE TITLE
Missing steps for installation / ModuleNotFoundError: No module named 'pyoverkiz.const'; 'pyoverkiz' is not a package

### ISSUE THREAD

**Issue by Anthael** [iMicknl/python-overkiz-api#691]
Hi 

According the readme file, I m running debian 11 with python 3.9  on a virtual machine and I try to get running the overkiz api.

To replicate the problem you can do the followings actions :

1) Open a session with a standard user ( no root )

2) Install package 
pip install pyoverkiz

3) create test script into test.py and paste the code provided on the readme file

4) run the script
python test.py

Result 
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/xxx/test.py", line 14, in <module>
    from pyoverkiz.client import OverkizClient
  File "/home/xxx/pyoverkiz.py", line 4, in <module>
    from pyoverkiz.const import SUPPORTED_SERVERS
ModuleNotFoundError: No module named 'pyoverkiz.const'; 'pyoverkiz' is not a package

I guess it s missing to set some varaibles to handle the correct path to the package

Thanks by advance

**Comment by iMicknl** [comment]
> I guess it s missing to set some varaibles to handle the correct path to the package

This should not be required. PyOverkiz is like a normal python package that you can install via `pip install pyoverkiz`. Do you have experience with Python and have you been able to install and run other packages before?

**Comment by Anthael** [comment]
It s the first repo i used on this virtual machine and i have installed it from scratch.
It should work as it is but.

Could you help me to create a virtual env ?
Thanks by advance

**Comment by iMicknl** [comment]
https://docs.python.org/3/library/venv.html
