### ISSUE TITLE
Atlantic Cozytouch not available ?

### ISSUE THREAD

**Issue by KostadinovicNikola** [iMicknl/python-overkiz-api#806]
Hello, i'm trying to access the server altantic_cozytouch, but it tell me this error: Cannot connect to host apis.groupe-atlantic.com:443 ssl:default [The specified network name is no longer available.]

It's only me or not ?

**Comment by KostadinovicNikola** [comment]
Yes, i don't know if it's my username and password, or maybe something else.

**Comment by iMicknl** [comment]
This error is not related to your username and password, but to your network configuration. Would be good to double check if that host is reachable from other systems.

**Comment by KostadinovicNikola** [comment]
Do you know how to setup the proxy adress to use or not?

**Comment by KostadinovicNikola** [comment]
Ok it's good, i have access to my devices, i wanted to know if there is a getter for like the energy consumption etc.. ? i can't find it. @iMicknl
