### ISSUE TITLE
Write in cozytouch

### ISSUE THREAD

**Issue by KostadinovicNikola** [iMicknl/python-overkiz-api#810]
Hello, is there a way to write in cozytouch, like to change the target temperature of a heater for example.

**Comment by iMicknl** [comment]
Yes, you can execute a command. You could have a look at the Home Assistant code (https://github.com/home-assistant/core/tree/dev/homeassistant/components/overkiz) for an example.

**Comment by KostadinovicNikola** [comment]
Thank you, it helped a lot and it works !!!!
